on: [push]

jobs:
  setup-sfdx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    name: OS ${{ matrix.os }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup sfdx
        uses: ./actions/setupsfdx
      - name: Check sfdx
        run: sfdx version
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Setup sfdx
        uses: ./actions/setupsfdx
      - name: Verify node
        run: which node && which npm && which sfdx
      - name: Check path
        run: echo $PATH
      - name: Verify npm
        run: npm --version
      - name: Verify sfdx
        run: sfdx version
