on: [push]

jobs:
  setup-sfdx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    name: setup sfdx
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup sfdx
        uses: ./actions/setupsfdx
      - name: Verify sfdx
        run: which sfdx
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Verify node
        run: which node && which npm && which sfdx
      - name: Check path
        run: echo $PATH
      - name: Verify npm
        run: npm --version
