on: [push]

jobs:
  setup-sfdx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    name: setup sfdx
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup sfdx
        uses: ./actions/setupsfdx
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Verify node
        run: npm --version
      - name: Verify sfdx
        run: sfdx version
